"use client";
import { ArrowUpRight, Copy, Check } from "lucide-react";
import { useState } from "react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const contents = [
  ["overview", "Overview"], ["venues", "Supported launchpad"], ["routing", "Fee routing"],
  ["recipient", "Naming the recipient"], ["split", "The 80/20 split"], ["collection", "Fee collection"],
  ["verification", "Telegram verification"], ["claim", "Claiming your balance"], ["unclaimed", "Unclaimed fees"],
  ["records", "Records & receipts"], ["treasury", "The project treasury"], ["tele", "TELE"],
  ["troubleshooting", "Troubleshooting"], ["glossary", "Glossary"], ["faq", "Questions"]
];
export function DocsContent({go,live=false}:{go:(route:string)=>void;live?:boolean}) {
  const [copied,setCopied]=useState(false);
  async function copyLine(){try{await navigator.clipboard.writeText("Fees to @yourhandle via TelePaid");setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setCopied(false);}}
  return <div className="page-content docs-page">
    <div className="page-title"><div><h1>How TelePaid works</h1><p>Creator fees for a Telegram account. Verified by its owner. Claimed on Solana.</p></div></div>
    {!live&&<div className="docs-release"><span>Interface preview</span><p>The mechanism below describes the intended product. Live launching, Telegram authentication, fee collection, and payouts are not connected in this release.</p></div>}
    <div className="docs-layout"><aside aria-label="Documentation contents">{contents.map(([id,title])=><a key={id} href={"#docs-"+id}>{title}</a>)}</aside><article>
      <section id="docs-overview"><h2>Fees follow the username.</h2><p>A token can be launched for any Telegram account. TelePaid records the creator fees it receives from that token, assigns 80% to the named account, and retains 20% for the project. The account owner visits TelePaid to verify and claim.</p><p>Launching a token and claiming its fees are separate actions. The launcher supplies the recipient. Only the verified recipient can withdraw that account’s balance.</p></section>
      <section id="docs-venues"><h2>Launch on Solana</h2><p>Pump.fun on Solana is the launch venue for TelePaid. The launch form collects a name, ticker, image, description, and Telegram recipient. Optional social links and an initial buy can be included.</p><button className="btn outline" onClick={()=>go("launch")}>Open launch form <ArrowUpRight size={15}/></button></section>
      <section id="docs-routing"><h2>From trading to creator fees</h2><p>Trading volume and creator fees are different amounts. The 80/20 split applies only to the creator fees TelePaid actually receives; it does not apply to the entire value of a trade.</p><p>New launches set your connected wallet as the initial Pump creator. In the same transaction, official Pump Fee Sharing routes 100% of creator fees to the TelePaid treasury and revokes the creator’s ability to edit those shares. Your optional initial buy executes after this routing is configured. A token’s description alone cannot move funds or prove routing. Every TelePaid mint ends in TeLe. The suffix is branding; verify its registered launch and fee destination to establish authenticity.</p></section>
      <section id="docs-recipient"><h2>Name the Telegram recipient</h2><p>Enter the exact Telegram username or paste a t.me profile link, then select the returned profile in the launch form. This identifies the intended recipient; it does not establish ownership or imply that the account endorses the token.</p><div className="docs-code"><code>Fees to @yourhandle via TelePaid</code><button aria-label="Copy recipient line" onClick={copyLine}>{copied?<Check size={17}/>:<Copy size={17}/>}</button></div><p>This attribution line and the structured recipient field identify the username in token metadata. The recipient can be named before joining TelePaid, then sign in later to establish ownership.</p></section>
      <section id="docs-split"><h2>The 80/20 split</h2><p>For every 1 SOL of received creator fees, 0.80 SOL is allocated to the Telegram account owner and 0.20 SOL to TelePaid. The recipient balance is the amount after this split.</p><div className="docs-split"><span>Telegram recipient<strong>80%</strong></span><span>TelePaid project<strong>20%</strong></span></div><p className="split-example">Example: 10 SOL received → 8 SOL for the recipient + 2 SOL for the project.</p><p>The project share is accounted for separately. Claiming an already allocated recipient balance does not apply the 20% split a second time.</p></section>
      <section id="docs-collection"><h2>Collection and allocation</h2><p>The ledger records each token, finalized collection, gross amount received, and both shares. Fees accumulate in a per-token Pump sharing vault until distributed to the treasury. Recipient earnings increase only after a collection is finalized. Failed or duplicate transactions must not create additional credit.</p><p>Collection is TelePaid receiving creator fees. A recipient claim is a separate withdrawal from an existing balance.</p></section>
      <section id="docs-verification"><h2>Verify the person behind the handle</h2><p>Sign in with Telegram to prove control of the recipient account. Looking up a username is public and does not authorize a claim. Verification must be checked on the server, with the verified username matching the recipient handle.</p><p>Fees belong to the username. If it is sold, renamed, or reassigned, its current verified holder can claim the remaining unclaimed balance. Each new claim requires a fresh Telegram verification; old sessions cannot authorize new withdrawals indefinitely.</p></section>
      <section id="docs-claim"><h2>Claim to your Solana wallet</h2><ol className="docs-steps"><li>Sign in with Telegram and verify the recipient account.</li><li>Connect the Solana wallet that should receive the funds.</li><li>Review the available amount and destination, then authorize the claim.</li><li>Track confirmation and the updated remaining balance.</li></ol><p>Telegram is the identity step. Funds are claimed to a Solana wallet through TelePaid; no payment is sent in a Telegram chat. Funds transfer only after verification and an authorized claim.</p><button className="btn outline" onClick={()=>go("claims")}>Open claims <ArrowUpRight size={15}/></button></section>
      <section id="docs-unclaimed"><h2>Balances wait for their owner</h2><p>The recipient’s 80% stays allocated until that account is verified and a claim is completed. An unclaimed balance is not part of the project’s 20% share.</p><p>Unclaimed fees have no announced expiry. A username transfer includes the right to its unclaimed balance; completed or already reserved withdrawals remain with their recorded destination.</p></section>
      <section id="docs-records"><h2>A clear record of each step</h2><p>Fee collections show what TelePaid received. Creator earnings show the 80% allocation. Claims show what has been withdrawn. The available amount is earned minus settled and currently reserved claims.</p><p>Token and profile pages keep those amounts together. Live token pages link to their on-chain transactions. Sample listings remain labelled separately and do not represent real earnings.</p></section>
      <section id="docs-treasury"><h2>The project share</h2><p>TelePaid receives 20% of collected creator fees. This allocation is separate from money owed to Telegram recipients and is shown independently in Analytics.</p><p>The product currently targets Solana. There is no dollar off-ramp or cross-chain payout flow in this release.</p></section>
      <section id="docs-tele"><h2>Tele · TELE</h2><p>Tele is the project’s token name, with the ticker TELE and the TelePaid T mark. No live contract address, supply, distribution, or buyback policy has been announced in this preview.</p><button className="btn outline" onClick={()=>go("tele")}>View TELE <ArrowUpRight size={15}/></button></section>
      <section id="docs-troubleshooting"><h2>When something does not appear</h2><ul className="docs-list"><li><strong>Account not found:</strong> check the exact username. Use the same spelling, without spaces.</li><li><strong>Balance differs from fees collected:</strong> the recipient receives 80% of the gross collection. Completed claims reduce the available amount.</li><li><strong>Claim unavailable:</strong> identity, wallet authorization, and a live settlement connection are required. If payouts are paused, retry after service resumes.</li><li><strong>Token not registered:</strong> in the live product, check the recipient metadata and verified fee destination before investigating indexing delays.</li></ul></section>
      <section id="docs-glossary"><h2>A few useful terms</h2><dl className="glossary"><div><dt>Collected</dt><dd>Gross creator fees received by TelePaid.</dd></div><div><dt>Earned</dt><dd>The recipient’s 80% allocation, before withdrawals.</dd></div><div><dt>Claimed</dt><dd>Recipient funds already withdrawn to a Solana wallet.</dd></div><div><dt>Claimable</dt><dd>Earned minus claimed, subject to account verification.</dd></div><div><dt>Project share</dt><dd>The separate 20% allocation to TelePaid.</dd></div></dl></section>
      <section id="docs-faq"><h2>Common questions</h2><Accordion type="single" collapsible><AccordionItem value="launch"><AccordionTrigger>Can I launch for someone else?</AccordionTrigger><AccordionContent>Yes. Enter their Telegram username. Only the verified account owner can claim their allocated fees.</AccordionContent></AccordionItem><AccordionItem value="wallet"><AccordionTrigger>Does connecting a wallet verify Telegram ownership?</AccordionTrigger><AccordionContent>No. Telegram identity verification and wallet authorization are separate steps. Both are needed to claim.</AccordionContent></AccordionItem><AccordionItem value="split"><AccordionTrigger>Does the recipient pay the 20% again when claiming?</AccordionTrigger><AccordionContent>No. The recipient’s displayed earnings already represent their 80% allocation. The project share is separated when received fees are recorded.</AccordionContent></AccordionItem>{!live&&<AccordionItem value="live"><AccordionTrigger>Can this preview launch a token or pay me?</AccordionTrigger><AccordionContent>No. This hosted interface preview does not hold funds. The production service needs server configuration and a completed network test before activation.</AccordionContent></AccordionItem>}</Accordion></section>
    </article></div>
  </div>;
}
