"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {Home,Compass,Wallet,Rocket,BarChart3,BookOpen,Layers3,Menu,X,ArrowUpRight,Send,RefreshCw,CheckCircle2} from 'lucide-react';
import bs58 from 'bs58';
import {WalletButton,useTeleWallet} from './wallet-context';
import {digestPayload} from '@/lib/devnet-proof.mjs';
import {DocsContent} from '@/app/docs-content';
type Tx={id:string;kind:'create'|'buy'|'claim';status:string;transaction?:string;signature:string|null;amount:number;wallet:string;error?:string};
type Token={id:string;wallet:string;mint:string;name:string;symbol:string;description:string;handle:string;image:string;initial_buy:string;credited:number;created_at:number;transactions:Tx[]};
type State={tokens:Token[];balance:number|null;readyMints:number;networkWarning:string;testGross:number;testRecipient:number;testProject:number;telegram:{handle:string;expiresAt:number;fresh:boolean}|null};
const initialState:State={tokens:[],balance:null,readyMints:0,networkWarning:'',testGross:1000000,testRecipient:800000,testProject:200000,telegram:null};
const nav=[['home','Home',Home],['explore','Explore',Compass],['claims','Claims',Wallet],['analytics','Analytics',BarChart3],['launch','Launch',Rocket],['flow','Fee flow',Layers3],['tele','$TELE',Layers3],['docs','Docs',BookOpen]] as const;
const sol=(value:number|string)=>(Number(value)/1e9).toLocaleString('en-US',{maximumFractionDigits:9});
const txLink=(sig:string)=>'https://explorer.solana.com/tx/'+sig+'?cluster=devnet';
const mintLink=(mint:string)=>'https://explorer.solana.com/address/'+mint+'?cluster=devnet';
const getTx=(token:Token,kind:Tx['kind'])=>token.transactions.find(tx=>tx.kind===kind);
function Brand(){return <span className="brand"><img className="brand-mark" src="/telepaid-mark.png" alt=""/><span className="brand-word">TelePaid</span></span>}
async function api<T>(path:string,body?:unknown):Promise<T>{
 const response=await fetch('/api/devnet/'+path,{signal:AbortSignal.timeout(60000),...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});
 let result:any;try{result=await response.json()}catch{throw new Error('The test service could not be reached. Please retry.')}if(!response.ok)throw new Error(result.error||'The test request failed');return result as T;
}
export function DevnetApp(){
 const wallet=useTeleWallet(),[route,setRoute]=useState('home'),[menu,setMenu]=useState(false),[state,setState]=useState(initialState),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[sort,setSort]=useState('recent'),[botUrl,setBotUrl]=useState('');
 const [form,setForm]=useState({name:'',symbol:'',description:'',handle:'',image:'',initialBuy:'0'}),[imageName,setImageName]=useState(''),[selected,setSelected]=useState('');
 const intent=useRef<{digest:string;id:string}|null>(null),busyRef=useRef(false),refreshVersion=useRef(0);
 const view=route.split('/')[0];
 useEffect(()=>{setBotUrl('')},[wallet.address]);
 useEffect(()=>{if(state.telegram?.fresh)setBotUrl('')},[state.telegram?.fresh,state.telegram?.expiresAt]);
 const go=(next:string)=>{location.hash=next;setRoute(next);setMenu(false);setError('')};
 useEffect(()=>{const sync=()=>setRoute((location.hash.slice(1)||'home').replace(/^create$/,'launch'));sync();addEventListener('hashchange',sync);return()=>removeEventListener('hashchange',sync)},[]);
 const refresh=useCallback(async()=>{const version=++refreshVersion.current;const data=await api<State>('state'+(wallet.address?'?wallet='+encodeURIComponent(wallet.address):''));if(version===refreshVersion.current){setState(data);setLoaded(true)}},[wallet.address]);
 useEffect(()=>{let active=true;refresh().catch(e=>{if(active)setError(e.message)});const timer=setInterval(()=>{if(active)void refresh().catch(()=>{})},8000);return()=>{active=false;refreshVersion.current++;clearInterval(timer)}},[refresh]);
 async function run(label:string,fn:()=>Promise<void>){if(busyRef.current)return;busyRef.current=true;setBusy(label);setError('');setNotice('');try{await fn();await refresh()}catch(e){setError(e instanceof Error?e.message:'The request was cancelled. You can retry.')}finally{busyRef.current=false;setBusy('')}}
 async function signed<T>(action:string,payload:Record<string,unknown>):Promise<T>{
  const address=wallet.address;if(!address)throw new Error('Connect a Solana wallet first.');
  const full={...payload,wallet:address},digest=await digestPayload(full);
  const challenge=await api<{id:string;message:string}>('challenge',{wallet:address,action,digest});
  const signature=await wallet.signMessage(new TextEncoder().encode(challenge.message));
  return api<T>(action,{payload:full,proof:{id:challenge.id,signature:bs58.encode(signature)}});
 }
 async function submit(tx:Tx){
  if(tx.status!=='prepared'||!tx.transaction)return;
  const bytes=Uint8Array.from(atob(tx.transaction),c=>c.charCodeAt(0));
  const signature=await wallet.signTransaction(bytes);
  await api('submit',{id:tx.id,transaction:btoa(String.fromCharCode(...signature))});
  setNotice(tx.kind==='buy'?'Dev buy submitted. Waiting for Devnet finalization.':'Token creation submitted. Waiting for Devnet finalization.');
 }
 async function create(){
  if(!form.image)throw new Error('Upload a token image.');
  if(!/^\d+(\.\d{1,9})?$/.test(form.initialBuy||'0'))throw new Error('Enter a valid Devnet SOL amount.');
  const [whole,fraction='']=(form.initialBuy||'0').split('.');const initialBuy=(BigInt(whole)*1000000000n+BigInt(fraction.padEnd(9,'0'))).toString();
  if(BigInt(initialBuy)>1000000000n)throw new Error('Use at most 1 Devnet SOL for the dev buy.');
  const data={...form,handle:form.handle.trim().replace(/^@/,'').toLowerCase(),initialBuy,wallet:wallet.address};
  const digest=await digestPayload(data);if(intent.current?.digest!==digest)intent.current={digest,id:crypto.randomUUID()};
  const result=await signed<{launch:Token;transaction:Tx}>('prepare',{...data,requestId:intent.current.id});setSelected(result.launch.id);await refresh();await submit(result.transaction);
 }
 async function resume(token:Token){setSelected(token.id);const result=await signed<{transaction:Tx}>('resume',{id:token.id});await submit(result.transaction)}
 async function buy(token:Token){const result=await signed<{transaction:Tx}>('buy',{id:token.id});await submit(result.transaction)}
 async function credit(token:Token){await signed('credit',{id:token.id});setNotice('Test fee added: 0.001 Devnet SOL → 0.0008 for your test recipient + 0.0002 for TelePaid. This is simulated income.');}
 async function verifyTelegram(){const result=await signed<{url:string}>('telegram',{});setBotUrl(result.url);setNotice('Open TelePayFunBot using the button below. Press Start and confirm your wallet, then return here.');}
 async function claim(token:Token){await signed('claim',{id:token.id});setNotice('Claim submitted. The test treasury is sending 0.0008 Devnet SOL to your connected wallet.');}
 async function upload(file?:File){if(!file)return;if(file.size>2*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('Choose a PNG, JPG or WebP under 2 MB.');return;}const image=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});setForm(f=>({...f,image}));setImageName(file.name);setSelected('');}
 const mine=state.tokens.filter(t=>t.wallet===wallet.address),confirmed=state.tokens.filter(t=>getTx(t,'create')?.status==='confirmed');
 const claimTokens=state.tokens.filter(t=>t.wallet===wallet.address||t.handle===state.telegram?.handle||getTx(t,'claim')?.wallet===wallet.address);
 const credited=state.tokens.filter(t=>t.handle===state.telegram?.handle&&t.credited),claimed=state.tokens.filter(t=>getTx(t,'claim')?.wallet===wallet.address&&getTx(t,'claim')?.status==='confirmed'),pending=credited.filter(t=>['submitted','preparing'].includes(getTx(t,'claim')?.status||''));
 const available=credited.filter(t=>!['submitted','preparing','confirmed'].includes(getTx(t,'claim')?.status||'')).length;
 const active=state.tokens.find(t=>t.id===selected);
 const filtered=[...confirmed].filter(t=>(t.name+' '+t.symbol+' '+t.handle).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='fees'?b.credited-a.credited||b.created_at-a.created_at:b.created_at-a.created_at);
 const detail=state.tokens.find(t=>t.id===route.split('/')[1]);
 const card=(t:Token)=><button className="token-card" key={t.id} onClick={()=>go('token/'+t.id)}><div className="token-picture"><img className="live-token-img" src={t.image} alt={t.name}/><span className="recipient-chip"><Send size={12}/>@{t.handle}</span></div><div className="token-caption"><div><span>{t.name}</span><small>{t.symbol} · Devnet</small></div><div className="card-earned"><span>{t.credited?'0.0008':'0'} SOL</span><small>test allocation</small></div></div></button>;
 const empty=<div className="live-empty"><Rocket size={28}/><h3>Your first Devnet token starts here</h3><p>Create a real test token, add a simulated fee, and claim Devnet SOL.</p><button className="btn white" onClick={()=>go('launch')}>Create test token</button></div>;
 const status=(tx?:Tx)=><>{tx&&<div className="devnet-tx"><span>{tx.kind==='create'?'Token creation':tx.kind==='buy'?'Dev buy':'Claim'}</span><strong>{tx.status==='confirmed'?'Finalized':tx.status}</strong>{tx.signature&&<a className="text-link" href={txLink(tx.signature)} target="_blank" rel="noreferrer">View transaction ↗</a>}{tx.error&&<p className="form-error">{tx.error}</p>}</div>}</>;
 const actions=(token:Token)=>{const created=getTx(token,'create'),bought=getTx(token,'buy'),paid=getTx(token,'claim');return <div className="devnet-actions">{status(created)}{status(bought)}{status(paid)}{token.wallet===wallet.address&&<>
  {created?.status!=='confirmed'&&created?.status!=='submitted'&&<button className="btn white" disabled={!!busy} onClick={()=>void run('Preparing your token…',()=>resume(token))}>Resume creation</button>}
  {created?.status==='confirmed'&&BigInt(token.initial_buy)>0n&&!['submitted','confirmed'].includes(bought?.status||'')&&<button className="btn white" disabled={!!busy} onClick={()=>void run('Preparing your dev buy…',()=>buy(token))}>Dev buy · {sol(token.initial_buy)} SOL</button>}
  {created?.status==='confirmed'&&!token.credited&&<button className="btn outline" disabled={!!busy} onClick={()=>void run('Adding a test fee…',()=>credit(token))}>Add test fee · 0.001 SOL</button>}
 </>}{!!token.credited&&wallet.address&&state.telegram?.handle===token.handle&&state.telegram.fresh&&!['submitted','confirmed','preparing'].includes(paid?.status||'')&&<button className="btn white" disabled={!!busy} onClick={()=>void run('Submitting your claim…',()=>claim(token))}>Claim 0.0008 Devnet SOL</button>}
  {paid?.status==='preparing'&&paid.wallet===wallet.address&&<button className="btn outline" disabled={!!busy} onClick={()=>void run('Resuming your claim…',()=>claim(token))}>Resume claim</button>}
  {paid?.status==='confirmed'&&paid.wallet===wallet.address&&<p className="wallet-test-success"><CheckCircle2 size={16}/> Test claim finalized.</p>}
 {!!token.credited&&wallet.address&&!['submitted','confirmed','preparing'].includes(paid?.status||'')&&(!state.telegram?.fresh||state.telegram.handle!==token.handle)&&<button className="btn outline" disabled={!!busy} onClick={()=>void run('Preparing Telegram verification…',verifyTelegram)}>Verify @{token.handle} to claim</button>}
 </div>};
 return <div className="app-shell live-app"><a className="skip-link" href="#main">Skip to content</a>{menu&&<button className="mobile-scrim" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}
 <aside className={'sidebar '+(menu?'open':'')}><button className="sidebar-brand" onClick={()=>go('home')}><Brand/></button><nav aria-label="Main navigation">{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>go(id)}><Icon size={23}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><Brand/></div></aside>
 <div className="main-shell"><header className="topbar"><button className="mobile-menu" aria-label="Open menu" onClick={()=>setMenu(true)}><Menu/></button><div className="search-box"><input aria-label="Search test tokens" placeholder="Search tokens or Telegram usernames" value={search} onChange={e=>{setSearch(e.target.value);if(view!=='explore')go('explore')}}/></div><div className="header-actions"><span className="devnet-pill">DEVNET</span><button className="btn white" onClick={()=>go('launch')}>Launch</button><WalletButton className="btn outline"/></div></header>
 <div className="devnet-banner"><strong>Devnet testing is live.</strong><span>Real test tokens & payouts. Simulated fee income. Verify your Telegram username to claim.</span><a href="https://faucet.solana.com/" target="_blank" rel="noreferrer">Get Devnet SOL ↗</a></div>
 <main id="main">{botUrl&&<div className="live-message"><a className="btn white" href={botUrl} target="_blank" rel="noreferrer">Open TelePayFunBot ↗</a><span>Press Start, confirm your wallet and username, then return to this page.</span></div>}{error&&<div className="live-message error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="live-message" role="status">{notice}</div>}{busy&&<div className="live-message" role="status"><RefreshCw size={16}/>{busy} Check your wallet for a signature request.</div>}{state.networkWarning&&<div className="live-message">{state.networkWarning}</div>}
 {!loaded&&<div className="live-empty"><h2>Loading the Devnet test environment</h2><button className="btn outline" onClick={()=>void run('Refreshing…',refresh)}>Retry</button></div>}
 {loaded&&<>
 {(view==='home'||view==='explore')&&<div className="page-content">{view==='home'?<><div className="live-hero"><div><h1>Route token fees<br/>to <em>Telegram</em></h1><p>Try the complete flow on Solana Devnet.<br/>Create a token. Add a test fee. Claim your 80%.</p><button className="btn white" onClick={()=>go('launch')}>Create test token <ArrowUpRight size={16}/></button></div><div className="live-signin-panel"><Send size={30}/><h2>Your first test, end to end.</h2><p>Use a wallet funded with Devnet SOL. Verify your Telegram account in TelePayFunBot, then claim to your connected wallet.</p><button className="btn outline full" onClick={()=>go('claims')}>Open test claims</button></div></div><div className="fee-summary"><div className="fee-summary-item"><Send/><span><strong>80% test recipient allocation</strong><small>The verified Telegram username owner claims to their connected wallet.</small></span></div><div className="fee-summary-item"><Layers3/><span><strong>20% project allocation</strong><small>The simulated fee is split once, with an exact on-chain test payout.</small></span></div><div className="fee-summary-item"><Rocket/><span><strong>Pump on Solana Devnet</strong><small>Real token creation. Every mint ends in TeLe.</small></span></div></div></>:<div className="page-title"><h1>Explore test tokens</h1><p>Finalized tokens created on Pump's Devnet program.</p></div>}
 <div className="section-head"><h2>{view==='home'?'Latest test tokens':'Devnet tokens'}</h2><button className="text-link" onClick={()=>void run('Refreshing…',refresh)}><RefreshCw size={16}/> Refresh</button></div><div className="token-sort-bar"><div className="devnet-sort"><button className={sort==='recent'?'active':''} onClick={()=>setSort('recent')}>Recent</button><button className={sort==='fees'?'active':''} onClick={()=>setSort('fees')}>Test fees</button></div><span>Market cap and latest-trade data are not connected in this test environment.</span></div>{filtered.length?<div className="token-grid explore-grid">{filtered.map(card)}</div>:empty}</div>}
 {view==='launch'&&<div className="page-content"><div className="page-title"><h1>Launch a test token</h1><p>Create on Pump's Devnet program. No mainnet funds are used.</p></div><div className="devnet-balance"><span>Wallet balance: <strong>{wallet.address?(state.balance===null?'Loading…':sol(state.balance)+' Devnet SOL'):'Connect your wallet'}</strong></span><span>{state.readyMints} TeLe addresses ready</span></div>
 <div className="launch-layout"><div className="launch-form"><div className="form-title"><h2>Token details</h2><span className="devnet-pill">DEVNET</span></div><label className="field">Token image<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!!busy} onChange={e=>void upload(e.target.files?.[0])}/><small>{imageName||'PNG, JPG or WebP. Up to 2 MB.'}</small></label><div className="form-grid"><label className="field">Token name<input disabled={!!busy} maxLength={32} placeholder="My test token" value={form.name} onChange={e=>{setSelected('');setForm({...form,name:e.target.value})}}/></label><label className="field">Ticker<input disabled={!!busy} maxLength={10} placeholder="TELE" value={form.symbol} onChange={e=>{setSelected('');setForm({...form,symbol:e.target.value.toUpperCase()})}}/></label></div><label className="field">Description · optional<textarea disabled={!!busy} maxLength={1000} rows={3} value={form.description} onChange={e=>{setSelected('');setForm({...form,description:e.target.value})}}/></label><label className="field">Telegram recipient username<input disabled={!!busy} placeholder="@your_username" maxLength={33} value={form.handle} onChange={e=>{setSelected('');setForm({...form,handle:e.target.value})}}/></label><p className="field-help">Enter any Telegram username. Its current owner must verify in TelePayFunBot before claiming. You do not need their Telegram ID.</p><label className="field">Dev buy · Devnet SOL<input disabled={!!busy} inputMode="decimal" value={form.initialBuy} onChange={e=>{setSelected('');setForm({...form,initialBuy:e.target.value})}}/></label><p className="field-help">Optional, up to 1 Devnet SOL. Token creation and the dev buy use separate signatures. The buy allows 1% slippage. Network fees and account rent are additional.</p>
 {!wallet.address?<WalletButton className="btn white full"/>:<button className="btn white full" disabled={!!busy||!state.readyMints} onClick={()=>void run('Preparing your token…',create)}>{busy?'Check your wallet…':'Create on Devnet'}</button>}{!state.readyMints&&<p className="field-help">The mint pool is being refilled. You can resume existing tests below.</p>}</div>
 <aside className="launch-summary"><h3>Token preview</h3><div className="launch-art">{form.image?<img src={form.image} alt="Token preview"/>:<Brand/>}</div><h2>{form.name||'Your test token'}</h2><p>{form.symbol||'TOKEN'}</p><dl><div><dt>Recipient label</dt><dd>@{form.handle.replace(/^@/,'')||'username'}</dd></div><div><dt>Network</dt><dd>Solana Devnet</dd></div><div><dt>Suffix</dt><dd>TeLe</dd></div><div><dt>Fee split</dt><dd>80% / 20%</dd></div></dl>{active&&<div className="review-result"><a className="text-link live-address" href={mintLink(active.mint)} target="_blank" rel="noreferrer">{active.mint} ↗</a>{actions(active)}</div>}</aside></div>
 {!!mine.length&&<><div className="section-head"><h2>Your saved tests</h2></div><div className="devnet-test-list">{mine.map(t=><div className="live-claim-box" key={t.id}><div className="devnet-test-title"><img src={t.image} alt=""/><div><h3>{t.name} · {t.symbol}</h3><p>@{t.handle} · <a href={mintLink(t.mint)} target="_blank" rel="noreferrer">View mint ↗</a></p></div></div>{actions(t)}</div>)}</div></>}</div>}
 {view==='claims'&&<div className="page-content"><div className="page-title"><h1>Claim test fees</h1><p>Verify the recipient Telegram username. Each test claim sends 0.0008 Devnet SOL to your connected wallet.</p></div><div className="metrics-grid"><div className="metric"><span>Available test allocation</span><strong>{sol(available*state.testRecipient)} SOL</strong></div><div className="metric"><span>Pending payout</span><strong>{sol(pending.length*state.testRecipient)} SOL</strong></div><div className="metric"><span>Finalized test claims</span><strong>{sol(claimed.length*state.testRecipient)} SOL</strong></div></div><div className="live-claim-box"><h2>{state.telegram?.fresh?'Verified @'+state.telegram.handle:'Verify your Telegram account'}</h2><p>{state.telegram?.fresh?'Fresh verification is ready for one claim.':'Confirm your current username and wallet in TelePayFunBot. Each claim needs a fresh verification within two minutes.'}</p>{wallet.address&&<button className="btn outline" disabled={!!busy} onClick={()=>void run('Preparing Telegram verification…',verifyTelegram)}>{state.telegram?.fresh?'Verify again':'Verify with Telegram'}</button>}</div>{!wallet.address?<WalletButton className="btn white"/>:claimTokens.length?<div className="devnet-test-list">{claimTokens.map(t=><div className="live-claim-box" key={t.id}><div className="devnet-test-title"><img src={t.image} alt=""/><div><h3>{t.name}</h3><p>@{t.handle} · {t.credited?'Test fee allocated':'No test fee added yet'}</p></div></div>{actions(t)}</div>)}</div>:empty}</div>}
 {view==='token'&&<div className="page-content">{detail?<><div className="token-detail-head"><img className="live-detail-img" src={detail.image} alt={detail.name}/><div><h1>{detail.name} <span>{detail.symbol}</span></h1><p>Fees for @{detail.handle} · Telegram verification required</p><p className="live-address">{detail.mint}</p></div><a className="btn outline" href={mintLink(detail.mint)} target="_blank" rel="noreferrer">View on Devnet ↗</a></div><p>{detail.description}</p>{actions(detail)}</>:<div className="live-empty">Test token not found.</div>}</div>}
 {(view==='analytics'||view==='flow')&&<div className="page-content"><div className="page-title"><h1>{view==='flow'?'Test the fee flow':'Devnet analytics'}</h1><p>Real Devnet transactions, with explicitly simulated fee income.</p></div><div className="metrics-grid"><div className="metric"><span>Finalized test tokens</span><strong>{confirmed.length}</strong></div><div className="metric"><span>Simulated gross fees</span><strong>{sol(state.tokens.filter(t=>t.credited).length*state.testGross)} SOL</strong></div><div className="metric"><span>Recipient allocation</span><strong>80%</strong></div><div className="metric"><span>Project allocation</span><strong>20%</strong></div></div><div className="live-claim-box"><h2>Run your test</h2><ol className="devnet-steps"><li>Connect a wallet with Devnet SOL.</li><li>Create a token for your Telegram username. Approve the wallet proof and creation transaction.</li><li>After finalization, optionally complete your dev buy.</li><li>Add a simulated 0.001 SOL fee. The app allocates 0.0008 to your test recipient and 0.0002 to TelePaid.</li><li>Verify the recipient username in TelePayFunBot, then claim the 0.0008 Devnet SOL and open its transaction receipt.</li></ol><p>These fees are test credits backed by a Devnet treasury. Telegram verification is real. Fee income is simulated here; automatic collection of actual trading fees remains a separate release requirement.</p><button className="btn white" onClick={()=>go('launch')}>Start a test</button></div></div>}
 {view==='tele'&&<div className="page-content"><div className="tele-brand-panel"><Brand/><div><h1>Tele · TELE</h1><p>No official TELE token has been launched. All tokens shown here are Devnet tests.</p></div></div></div>}
 {view==='docs'&&<><div className="page-content"><div className="data-note">The docs below describe the full product. This deployment runs the Devnet sandbox: Telegram verification and Devnet payouts are active; actual trading-fee collection is not active.</div><button className="btn outline" onClick={()=>go('flow')}>Devnet testing guide</button></div><DocsContent go={go} live/></>}
 </>}
 </main><footer><div><Brand/><p>Token fees for Telegram creators.</p><p>Devnet testing · Independent of Telegram.</p></div><div><span>Test environment</span><button onClick={()=>go('launch')}>Create token</button><button onClick={()=>go('claims')}>Test claims</button></div><div><span>Test allocation</span><strong>80% / 20%</strong><p>Devnet SOL has no monetary value.</p></div></footer></div></div>;
}
