'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowUpRight,ExternalLink,Globe2,Send} from 'lucide-react';
import {request,asSOL,TokenClaimAction,TransactionLink,usePlatform} from './platform-actions';
import {CopyAddress} from './copy-address';
import {TokenMarket,TokenStats,type Market} from './token-market';
import type {PublicToken} from '@/app/data';

export function LiveTokenDetail({id,go,onVerify}:{id:string;go:(route:string)=>void;onVerify:(claimAfterVerification?:boolean,recipient?:string)=>void}){
 const [market,setMarket]=useState<Market|null>(null);const {runtime}=usePlatform();const [token,setToken]=useState<PublicToken|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;setToken(null);setMarket(null);setError('');void request<PublicToken>(`/api/public/token/${encodeURIComponent(id)}`).then(row=>{if(active)setToken(row)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[id,attempt]);
 if(!token)return <div className="page-content"><button className="back-link" onClick={()=>go('explore')}><ArrowLeft size={16}/> All tokens</button><div className="empty-state" role="status"><h2>{error||'Loading token…'}</h2>{error&&<button className="btn outline" onClick={()=>setAttempt(n=>n+1)}>Try again</button>}</div></div>;
 const project=(BigInt(token.collected_lamports)-BigInt(token.earned_lamports)).toString();
 return <div className="page-content"><button className="back-link" onClick={()=>go('explore')}><ArrowLeft size={16}/> All tokens</button>
 <div className="token-detail-head"><img src={token.image_uri} className="detail-art" alt={token.name}/><div><h1>{token.name} <span>{token.symbol}</span></h1><div className="token-identity-links"><CopyAddress address={token.mint}/>{token.socials&&Object.values(token.socials).some(Boolean)&&<nav className="token-social-links" aria-label="Token links">{token.socials.website&&<a href={token.socials.website} target="_blank" rel="noopener noreferrer" aria-label={`${token.name} website`} title="Website"><Globe2 size={17}/></a>}{token.socials.twitter&&<a href={token.socials.twitter} target="_blank" rel="noopener noreferrer" aria-label={`${token.name} on X`} title="X"><span className="token-x-mark" aria-hidden="true">𝕏</span></a>}{token.socials.telegram&&<a href={token.socials.telegram} target="_blank" rel="noopener noreferrer" aria-label={`${token.name} on Telegram`} title="Telegram"><Send size={16}/></a>}</nav>}</div><p><span className="pump-tag"><img className="pump-logo" src="/pump-fun-logo.png" alt="" aria-hidden="true"/> Pump</span><span>Solana · {runtime?.cluster==='devnet'?'Devnet':'Mainnet'}</span><span>Created {new Date(token.confirmed_at).toLocaleString()}</span></p>{token.source==='official'?<span className="status-tag">Official TelePay token</span>:<button className="text-link" onClick={()=>go('account/'+token.recipient_handle)}><Send size={15}/> Fees for @{token.recipient_handle} <ArrowUpRight size={14}/></button>}</div><a className="btn outline" href={`https://pump.fun/coin/${token.mint}`} target="_blank" rel="noreferrer"><ExternalLink size={15}/> View on Pump</a></div>
 <TokenStats market={market}/><div className="data-note"><span className="status-tag">Live token</span> {token.source==='official'?'Finalized on Solana · Creator fees are managed by the project.':'Finalized on Solana · Earnings below are received fees, not estimates.'}</div>
 <div className="token-detail-grid"><div className="detail-chart"><TokenMarket key={id} id={id} symbol={token.symbol} onUpdate={setMarket}/><div className="live-token-facts"><p>{token.description||(token.source==='official'?'The official TelePay token.':`A token supporting @${token.recipient_handle} on Telegram.`)}</p><dl><div><dt>Mint address</dt><dd className="live-address"><CopyAddress address={token.mint} full/></dd></div><div><dt>Launch transaction</dt><dd><TransactionLink signature={token.signature} cluster={runtime?.cluster}/></dd></div></dl></div>{token.source==='official'?<div className="detail-description">The project manages this token directly. Telegram recipient claims do not apply.</div>:<div className="detail-description">80% of creator fees received from {token.name} are attributed to @{token.recipient_handle}. The current username owner can claim after Telegram verification.</div>}</div>
 {token.source==='official'?<div className="earnings-panel"><span>TELEPAY</span><strong>Official token</strong><dl><div><dt>Network</dt><dd>Solana</dd></div><div><dt>Mint suffix</dt><dd>TeLe</dd></div><div><dt>Creator</dt><dd><CopyAddress address={token.launcher_wallet||''}/></dd></div></dl><p>Creator fees for this token stay with the project treasury.</p></div>:<div className="earnings-panel"><span>CREATOR EARNINGS</span><strong>{asSOL(token.earned_lamports)} <small>SOL</small></strong><dl><div><dt>Total collected</dt><dd>{asSOL(token.collected_lamports)} SOL</dd></div><div><dt>Project share · 20%</dt><dd>{asSOL(project)} SOL</dd></div><div><dt>Recipient share</dt><dd>80%</dd></div><div><dt>Mint suffix</dt><dd>TeLe</dd></div></dl><TokenClaimAction recipient={token.recipient_handle||''} onVerify={after=>onVerify(after,token.recipient_handle||undefined)}/><p>Claims combine the fees assigned to this username across its tokens.</p></div>}</div>
 {token.source!=='official'&&<><div className="section-head"><h2>Recipient</h2></div><button className="live-recipient" onClick={()=>go('account/'+token.recipient_handle)}><Send size={24}/><span><strong>@{token.recipient_handle}</strong><small>View account fees and tokens</small></span><ArrowUpRight size={18}/></button></>}</div>;
}

export function LiveAccount({handle,go,renderToken,onVerify}:{handle:string;go:(route:string)=>void;renderToken:(row:PublicToken)=>React.ReactNode;onVerify:()=>void}){
 const {session}=usePlatform();const verifiedOwner=session.user?.username?.toLowerCase()===handle.toLowerCase();
 const [profile,setProfile]=useState<{handle:string;balance:{earned:string;settled:string;reserved:string};tokens:PublicToken[]}|null>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;setProfile(null);setError('');void request(`/api/public/profile/${encodeURIComponent(handle)}`).then(p=>{if(active)setProfile(p)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[handle]);
 return <div className="page-content"><button className="back-link" onClick={()=>go('explore')}><ArrowLeft size={16}/> Explore</button><div className="page-title"><div><h1>@{handle}</h1><p>Creator fees assigned to this Telegram username.</p></div><button className="btn white" onClick={()=>verifiedOwner?go('claims'):onVerify()}><Send size={16}/> {verifiedOwner?'Claim':'Verify & claim'}</button></div>{error?<p role="alert">{error}</p>:!profile?<p role="status">Loading account…</p>:<><div className="metrics-grid"><div className="metric"><span>Total earned</span><strong>{asSOL(profile.balance.earned)} SOL</strong></div><div className="metric"><span>Claimed</span><strong>{asSOL(profile.balance.settled)} SOL</strong></div><div className="metric"><span>Available</span><strong>{asSOL((BigInt(profile.balance.earned)-BigInt(profile.balance.settled)-BigInt(profile.balance.reserved)).toString())} SOL</strong></div><div className="metric"><span>In settlement</span><strong>{asSOL(profile.balance.reserved)} SOL</strong></div></div><div className="section-head"><h2>Tokens for @{handle}</h2><a className="text-link" href={`https://t.me/${handle}`} target="_blank" rel="noreferrer">Open Telegram <ArrowUpRight size={15}/></a></div><div className="token-grid explore-grid">{profile.tokens.map(renderToken)}</div>{!profile.tokens.length&&<p>No confirmed launches for this username yet.</p>}</>}</div>;
}
