'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {Check,Send} from 'lucide-react';
import {request,usePlatform} from './platform-actions';
type Recipient={handle:string;name:string;photo:string|null;status:string};
export type RecipientChoice={handle:string;name:string;photo:string|null;status:'found'|'unconfirmed'};
export function RecipientPicker({value,onChange,onConfirm}:{value:string;onChange:(value:string)=>void;onConfirm?:(recipient:RecipientChoice)=>void}){
 const {runtime}=usePlatform();const bot=runtime?.telegramBotUsername||'UseTelePay_bot';
 const id=useId(),root=useRef<HTMLDivElement>(null);const [results,setResults]=useState<Recipient[]>([]),[selected,setSelected]=useState<RecipientChoice|null>(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[active,setActive]=useState(0),[retry,setRetry]=useState(0),[scope,setScope]=useState('telegram_exact');
 const handle=value.trim().replace(/^https?:\/\/(?:www\.)?(?:t\.me|telegram\.me)\//i,'').replace(/^@/,'').replace(/\/$/,'').toLowerCase();
 const canSelectManually=/^[a-z][a-z0-9_]{3,31}$/.test(handle)&&!results.some(row=>row.handle===handle);
 useEffect(()=>{let valid=true;setResults([]);setError('');setActive(0);if(selected?.handle!==handle)setSelected(null);if(handle.length<3){setLoading(false);return;}setLoading(true);const timer=setTimeout(()=>{void request<{results:Recipient[];scope:string}>(`/api/public/recipients?q=${encodeURIComponent(handle)}${retry?'&refresh=1':''}`).then(data=>{if(valid){setResults(data.results);setScope(data.scope)}}).catch(()=>{if(valid)setError('Telegram profile lookup is unavailable. Please retry.')}).finally(()=>{if(valid)setLoading(false)})},400);return()=>{valid=false;clearTimeout(timer)}},[handle,retry]);
 function select(row:RecipientChoice){onChange(row.handle);onConfirm?.(row);setSelected(row);setOpen(false);}
 return <div className="recipient-picker" ref={root} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false)}}><label className="field" htmlFor={id}>Telegram username</label><div className="handle-input"><Send size={17}/><span>@</span><input id={id} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={id+'-results'} aria-activedescendant={open&&results[active]?id+'-'+active:undefined} aria-describedby={id+'-hint'} autoComplete="off" placeholder={scope==='telegram_search'?'Search Telegram usernames':'Enter the full username'} maxLength={64} value={value} onFocus={()=>setOpen(true)} onChange={e=>{onChange(e.target.value.replace(/^@/,''));setSelected(null);setOpen(true)}} onKeyDown={e=>{if(e.key==='Escape')setOpen(false);if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive(i=>Math.max(0,Math.min(i+1,results.length-1)))}if(e.key==='ArrowUp'){e.preventDefault();setActive(i=>Math.max(0,i-1))}if(e.key==='Enter'&&open&&results[active]){e.preventDefault();select({...results[active],status:'found'})}}}/></div>
 {open&&<div className="recipient-dropdown"><div role="listbox" id={id+'-results'} aria-label="Telegram profiles">{results.map((r,i)=><button type="button" role="option" aria-selected={selected?.handle===r.handle&&selected.status==='found'} id={id+'-'+i} className={active===i?'active':''} key={r.handle} onMouseDown={e=>e.preventDefault()} onClick={()=>select({...r,status:'found'})}>{r.photo?<img src={r.photo} alt="" referrerPolicy="no-referrer"/>:<span className="recipient-avatar"><Send size={18}/></span>}<span><strong>{r.name}</strong><small>@{r.handle}</small></span><small>Profile found</small></button>)}{!loading&&canSelectManually&&<button type="button" role="option" aria-selected={selected?.handle===handle&&selected.status==='unconfirmed'} onMouseDown={e=>e.preventDefault()} onClick={()=>select({handle,name:handle,photo:null,status:'unconfirmed'})}><span className="recipient-avatar"><Send size={18}/></span><span><strong>Use @{handle} manually</strong><small>Profile not confirmed · check the username carefully</small></span></button>}</div>
 <p className="field-help" role="status">{loading?'Looking up Telegram profile…':handle.length<3?'Type at least 3 characters. Use the full username for an exact lookup.':error||(!results.length?'No profile could be confirmed. You can still choose the exact username manually.':'Choose a profile, or enter the exact username.')}</p>{!loading&&(error||!results.length)&&handle.length>=3&&<button className="text-link" type="button" onClick={()=>setRetry(n=>n+1)}>Retry lookup</button>}
 {!loading&&!results.length&&handle.length>=3&&<p className="field-help">Is this your account? <a className="text-link" href={`https://t.me/${bot}?start=recipient`} target="_blank" rel="noreferrer">Open @{bot}</a>, press Start, then retry. This makes your profile discoverable; it does not connect a wallet.</p>}
 </div>}
 {selected&&<div className="recipient-selected">{selected.photo?<img src={selected.photo} alt="Recipient profile" referrerPolicy="no-referrer"/>:<Send size={22}/>}<span><strong>{selected.status==='found'?selected.name:`@${selected.handle}`}</strong><small>{selected.status==='found'?`@${selected.handle} · Profile found`:'Profile not confirmed · Verify the spelling before launch'}</small></span>{selected.status==='found'&&<Check size={18} aria-label="Profile found"/>}</div>}
 <p className="field-help" id={id+'-hint'}>{scope==='telegram_search'?'Search Telegram usernames or paste a t.me profile link.':'Enter the full @username or paste a t.me profile link to find the recipient.'} Profile selection does not verify ownership for claims.</p></div>;
}
