'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {Check,Send} from 'lucide-react';
import {request} from './platform-actions';
type Recipient={handle:string;name:string;photo:string|null;status:string};
export function RecipientPicker({value,onChange,onConfirm}:{value:string;onChange:(value:string)=>void;onConfirm?:(handle:string)=>void}){
 const id=useId(),root=useRef<HTMLDivElement>(null);const [results,setResults]=useState<Recipient[]>([]),[selected,setSelected]=useState<Recipient|null>(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[active,setActive]=useState(0),[retry,setRetry]=useState(0),[scope,setScope]=useState('telegram_exact');
 const handle=value.trim().replace(/^https?:\/\/(?:www\.)?(?:t\.me|telegram\.me)\//i,'').replace(/^@/,'').replace(/\/$/,'').toLowerCase();
 useEffect(()=>{let valid=true;setResults([]);setError('');setActive(0);if(selected?.handle!==handle)setSelected(null);if(handle.length<3){setLoading(false);return;}setLoading(true);const timer=setTimeout(()=>{void request<{results:Recipient[];scope:string}>(`/api/public/recipients?q=${encodeURIComponent(handle)}${retry?'&refresh=1':''}`).then(data=>{if(valid){setResults(data.results);setScope(data.scope)}}).catch(()=>{if(valid)setError('Telegram profile lookup is unavailable. Please retry.')}).finally(()=>{if(valid)setLoading(false)})},400);return()=>{valid=false;clearTimeout(timer)}},[handle,retry]);
 function select(row:Recipient){onChange(row.handle);onConfirm?.(row.handle);setSelected(row);setOpen(false);}
 return <div className="recipient-picker" ref={root} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false)}}><label className="field" htmlFor={id}>Telegram username</label><div className="handle-input"><Send size={17}/><span>@</span><input id={id} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={id+'-results'} aria-activedescendant={open&&results[active]?id+'-'+active:undefined} aria-describedby={id+'-hint'} autoComplete="off" placeholder={scope==='telegram_search'?'Search Telegram usernames':'Enter the full username'} maxLength={64} value={value} onFocus={()=>setOpen(true)} onChange={e=>{onChange(e.target.value.replace(/^@/,''));setSelected(null);setOpen(true)}} onKeyDown={e=>{if(e.key==='Escape')setOpen(false);if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive(i=>Math.max(0,Math.min(i+1,results.length-1)))}if(e.key==='ArrowUp'){e.preventDefault();setActive(i=>Math.max(0,i-1))}if(e.key==='Enter'&&open&&results[active]){e.preventDefault();select(results[active])}}}/></div>
 {open&&<div className="recipient-dropdown"><div role="listbox" id={id+'-results'} aria-label="Telegram profiles">{results.map((r,i)=><button type="button" role="option" aria-selected={selected?.handle===r.handle} id={id+'-'+i} className={active===i?'active':''} key={r.handle} onMouseDown={e=>e.preventDefault()} onClick={()=>select(r)}>{r.photo?<img src={r.photo} alt="" referrerPolicy="no-referrer"/>:<span className="recipient-avatar"><Send size={18}/></span>}<span><strong>{r.name}</strong><small>@{r.handle}</small></span><small>Profile found</small></button>)}</div>
 <p className="field-help" role="status">{loading?'Looking up Telegram profile…':handle.length<3?'Type at least 3 characters. Use the full username for an exact lookup.':error||(!results.length?'No profile could be confirmed for this search. This does not prove the username is available.':'Select a profile to confirm your recipient.')}</p>{!loading&&(error||!results.length)&&handle.length>=3&&<button className="text-link" type="button" onClick={()=>setRetry(n=>n+1)}>Retry lookup</button>}
 {!loading&&!results.length&&handle.length>=3&&<p className="field-help">Is this your account? <a className="text-link" href="https://t.me/TelePayFunBot?start=recipient" target="_blank" rel="noreferrer">Open TelePayFunBot</a>, press Start, then retry. This makes your profile discoverable; it does not connect a wallet.</p>}
 </div>}
 {selected&&<div className="recipient-selected">{selected.photo?<img src={selected.photo} alt="Recipient profile" referrerPolicy="no-referrer"/>:<Send size={22}/>}<span><strong>{selected.name}</strong><small>@{selected.handle} · {selected.status==='found'?'Profile found · Recipient selected':'Profile not confirmed'}</small></span><Check size={18}/></div>}
 <p className="field-help" id={id+'-hint'}>{scope==='telegram_search'?'Search Telegram usernames or paste a t.me profile link.':'Enter the full @username or paste a t.me profile link to find the recipient.'} Profile selection does not verify ownership for claims.</p></div>;
}
