'use client';
import {useEffect,useRef,useState} from 'react';
import {createChart,CandlestickSeries,HistogramSeries,ColorType,CrosshairMode,type UTCTimestamp,type IChartApi,type ISeriesApi} from 'lightweight-charts';
import {ArrowUpRight,RefreshCw,Maximize2} from 'lucide-react';
import {request,asSOL,usePlatform} from './platform-actions';
type Candle={time:number;open:number;high:number;low:number;close:number;volumeUsd:number;trades:number};
type Trade={signature:string;eventIndex:number;time:number;side:'buy'|'sell';wallet:string;solLamports:string;tokenRaw:string;priceUsd:number|null;volumeUsd:number|null};
export type Market={updatedAt:string;stale:boolean;indexing:boolean;spotPriceUsd:number|null;graduated:boolean;candles:Candle[];trades:Trade[];usdHistoryComplete:boolean;stats:{marketCapUsd:number|null;volume24hUsd:number|null;change24h:number|null;holders:number|null;holdersAt:string|null}};
export const usd=(n:number|null|undefined)=>n==null?'—':n===0?'$0':n<0.001?'$'+n.toFixed(10).replace(/0+$/,''):n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n<1?6:2});
const short=(s:string)=>`${s.slice(0,4)}…${s.slice(-4)}`;
export function TokenStats({market}:{market:Market|null}){
 const stats=market?.stats;const holderStale=!stats?.holdersAt||Date.now()-new Date(stats.holdersAt).getTime()>600000;
 return <dl className="token-stat-bar" aria-label="Token market statistics"><div><dt>Price <small>USD</small></dt><dd>{usd(market?.spotPriceUsd)}</dd></div><div><dt>Market cap</dt><dd>{usd(stats?.marketCapUsd)}</dd></div><div><dt>24h change</dt><dd className={(stats?.change24h??0)<0?'trade-sell':'trade-buy'}>{stats?.change24h==null?'—':`${stats.change24h>0?'+':''}${stats.change24h.toFixed(2)}%`}</dd></div><div><dt>24h volume</dt><dd>{market?.indexing?<small>Indexing…</small>:usd(stats?.volume24hUsd)}</dd></div><div title="Unique wallet owners with positive balances. Program-controlled accounts are excluded."><dt>Holders</dt><dd>{holderStale?'—':stats?.holders?.toLocaleString()??'—'}</dd></div></dl>;
}
function Candles({candles,interval}:{candles:Candle[];interval:number}){
 const container=useRef<HTMLDivElement>(null),chart=useRef<IChartApi|null>(null),series=useRef<ISeriesApi<'Candlestick'>|null>(null),volume=useRef<ISeriesApi<'Histogram'>|null>(null),fitted=useRef(false);const [hover,setHover]=useState<Candle|null>(null);
 useEffect(()=>{
  if(!container.current)return;
  const api=createChart(container.current,{autoSize:true,height:360,layout:{background:{type:ColorType.Solid,color:'#1B1E23'},textColor:'#A0A7B0',fontFamily:'Inter, sans-serif',fontSize:11,attributionLogo:true},grid:{vertLines:{color:'#252A30'},horzLines:{color:'#252A30'}},crosshair:{mode:CrosshairMode.Normal,vertLine:{color:'#7D8793',labelBackgroundColor:'#30363D'},horzLine:{color:'#7D8793',labelBackgroundColor:'#30363D'}},rightPriceScale:{borderColor:'#30363D',scaleMargins:{top:0.12,bottom:0.26}},timeScale:{borderColor:'#30363D',timeVisible:true,secondsVisible:false,rightOffset:5},localization:{priceFormatter:(n:number)=>usd(n)}});
  const prices=api.addSeries(CandlestickSeries,{upColor:'#42C99A',downColor:'#F07887',wickUpColor:'#42C99A',wickDownColor:'#F07887',borderVisible:false,priceFormat:{type:'custom',minMove:0.000000000001,formatter:(n:number)=>usd(n)}});
  const volumes=api.addSeries(HistogramSeries,{priceFormat:{type:'volume'},priceScaleId:'volume',lastValueVisible:false,priceLineVisible:false});volumes.priceScale().applyOptions({scaleMargins:{top:0.82,bottom:0},visible:false});
  api.subscribeCrosshairMove(param=>{const p=param.seriesData.get(prices);if(p&&'open' in p)setHover({...p,time:Number(param.time),volumeUsd:0,trades:0} as Candle);else setHover(null);});chart.current=api;series.current=prices;volume.current=volumes;fitted.current=false;
  return()=>{api.remove();chart.current=null;series.current=null;volume.current=null};
 },[interval]);
 useEffect(()=>{series.current?.setData(candles.map(c=>({...c,time:c.time as UTCTimestamp})));volume.current?.setData(candles.map(c=>({time:c.time as UTCTimestamp,value:c.volumeUsd,color:c.close>=c.open?'#42C99A44':'#F0788744'})));if(candles.length&&!fitted.current){chart.current?.timeScale().fitContent();fitted.current=true;}},[candles,interval]);
 const selected=hover||candles.at(-1);
 return <><div className="candle-readout" aria-live="off">{selected?(['open','high','low','close'] as const).map((key,i)=><span key={key}>{['O','H','L','C'][i]} <b>{usd(selected[key])}</b></span>):<span>No USD candles available yet</span>}<button className="chart-fit" onClick={()=>chart.current?.timeScale().fitContent()} aria-label="Fit chart to all trades" title="Fit chart"><Maximize2 size={14}/></button></div><div ref={container} className="candlestick-canvas" role="img" aria-label="Interactive token candlestick chart in US dollars. Drag to pan and scroll to zoom."/></>;
}
export function TokenMarket({id,symbol,onUpdate}:{id:string;symbol:string;onUpdate?:(market:Market)=>void}){
 const {runtime}=usePlatform();const [market,setMarket]=useState<Market|null>(null),[error,setError]=useState(''),[interval,setIntervalValue]=useState(60),[retry,setRetry]=useState(0),[loading,setLoading]=useState(true);const update=useRef(onUpdate);update.current=onUpdate;
 useEffect(()=>{let active=true,busy=false;setLoading(true);setError('');async function refresh(){if(busy)return;busy=true;try{const next=await request<Market>(`/api/public/token/${encodeURIComponent(id)}/market?interval=${interval}`);if(active){setMarket(next);update.current?.(next);setError('');}}catch{if(active)setError('Market data is temporarily unavailable.')}finally{busy=false;if(active)setLoading(false);}}void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},15000);return()=>{active=false;clearInterval(timer)}},[id,interval,retry]);
 const cluster=runtime?.cluster==='devnet'?'?cluster=devnet':'';
 return <section className="live-market" aria-label={`${symbol} price and trades`}>
 <div className="market-heading"><div><span>{symbol} / USD</span><strong>{usd(market?.spotPriceUsd)}</strong></div><div className="market-intervals" aria-label="Chart interval">{[[60,'1m'],[300,'5m'],[3600,'1h']].map(([value,label])=><button key={value} aria-pressed={interval===value} onClick={()=>setIntervalValue(Number(value))}>{label}</button>)}</div></div>
 {(error||market?.stale)&&<div className="market-message" role="status"><span>{error||'Showing the last available market data.'}</span><button className="text-link" onClick={()=>setRetry(n=>n+1)}><RefreshCw size={13}/> Retry</button></div>}
 {loading&&!market?<div className="market-chart"><p role="status">Loading on-chain market data…</p></div>:<Candles candles={market?.candles||[]} interval={interval}/>}
 <div className="market-caption"><span>{market?.indexing?'Backfilling finalized trades…':!market?.usdHistoryComplete?'USD history is updating…':'Finalized trades · USD conversion'}</span><span>Volume · USD</span></div>
 <p className="market-reference">USD values use Kraken SOL/USD; historical values use the matching 5-minute candle. {market?.stats.change24h==null?'24h change appears when a full day of history is available.':''}</p>
 <div className="market-trades-head"><h3>Trade history</h3><span>Pump{market?.graduated?' / PumpSwap':''} · Finalized</span></div>
 {market?.trades.length?<div className="market-table-scroll"><table className="market-table"><thead><tr><th>Time</th><th>Type</th><th>Price · USD</th><th>Total · USD</th><th>SOL</th><th>{symbol}</th><th>Trader</th><th>Txn</th></tr></thead><tbody>{market.trades.map(t=><tr key={`${t.signature}:${t.eventIndex}`}><td><time title={new Date(t.time*1000).toLocaleString()}>{new Date(t.time*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time></td><td className={`trade-${t.side}`}>{t.side==='buy'?'Buy':'Sell'}</td><td>{usd(t.priceUsd)}</td><td>{usd(t.volumeUsd)}</td><td>{asSOL(t.solLamports)}</td><td>{(Number(t.tokenRaw)/1e6).toLocaleString(undefined,{maximumFractionDigits:2})}</td><td><a href={`https://solscan.io/account/${t.wallet}${cluster}`} target="_blank" rel="noreferrer">{short(t.wallet)}</a></td><td><a href={`https://solscan.io/tx/${t.signature}${cluster}`} target="_blank" rel="noreferrer" aria-label={`View ${t.side} transaction on Solscan`}><ArrowUpRight size={14}/></a></td></tr>)}</tbody></table></div>:<p className="market-empty" role="status">{loading?'Loading trades…':error?'Trade history could not be loaded.':market?.indexing?'Indexing finalized transactions…':'No finalized trades found yet.'}</p>}
 <p className="chart-attribution"><a href="https://www.tradingview.com/" target="_blank" rel="noreferrer">TradingView Lightweight Charts™</a> · Copyright © 2025 TradingView, Inc.</p>
 </section>;
}
