'use client';
import {useEffect,useState} from 'react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {ArrowUpRight,RefreshCw} from 'lucide-react';
import {request,asSOL,usePlatform} from './platform-actions';
type Candle={time:number;open:number;high:number;low:number;close:number;volumeSol:number;trades:number};
type Trade={signature:string;eventIndex:number;time:number;side:'buy'|'sell';wallet:string;solLamports:string;tokenRaw:string;priceSol:number};
type Market={updatedAt:string;stale:boolean;indexing:boolean;spotPriceSol:number|null;lastTradePriceSol:number|null;graduated:boolean;candles:Candle[];trades:Trade[]};
const price=(n:number|null|undefined)=>n==null?'—':n===0?'0':n<0.000001?n.toExponential(4):n.toLocaleString(undefined,{maximumSignificantDigits:6});
const short=(s:string)=>`${s.slice(0,4)}…${s.slice(-4)}`;
export function TokenMarket({id,symbol}:{id:string;symbol:string}){
 const {runtime}=usePlatform();const [market,setMarket]=useState<Market|null>(null),[error,setError]=useState(''),[interval,setIntervalValue]=useState(60),[retry,setRetry]=useState(0),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true,busy=false;setMarket(null);setLoading(true);setError('');async function refresh(){if(busy)return;busy=true;try{const next=await request<Market>(`/api/public/token/${encodeURIComponent(id)}/market?interval=${interval}`);if(active){setMarket(next);setError('');}}catch{if(active)setError('Market data is temporarily unavailable.')}finally{busy=false;if(active)setLoading(false);}}void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},15000);return()=>{active=false;clearInterval(timer)}},[id,interval,retry]);
 const spot=market?.spotPriceSol??market?.lastTradePriceSol;
 const chart=market?.candles.length?market.candles:market?.spotPriceSol!=null?[{time:Math.floor(new Date(market.updatedAt).getTime()/1000),close:market.spotPriceSol}]:[];
 const cluster=runtime?.cluster==='devnet'?'?cluster=devnet':'';
 return <section className="live-market" aria-label={`${symbol} price and trades`}>
  <div className="market-heading"><div><span>{market?.graduated?'Last trade price':'Curve price'} · SOL / {symbol}</span><strong>{price(spot)} <small>SOL</small></strong></div><div className="market-intervals" aria-label="Chart interval">{[[60,'1m'],[300,'5m'],[3600,'1h']].map(([value,label])=><button key={value} aria-pressed={interval===value} onClick={()=>setIntervalValue(Number(value))}>{label}</button>)}</div></div>
  {(error||market?.stale)&&<div className="market-message" role="status"><span>{error||'Showing the last available market data.'}</span><button className="text-link" onClick={()=>setRetry(n=>n+1)}><RefreshCw size={13}/> Retry</button></div>}
  <div className="market-chart" aria-label="Token price in SOL">
   {loading&&!market?<p role="status">Loading on-chain market data…</p>:chart.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{top:24,right:8,bottom:8,left:12}}><defs><linearGradient id={`market-fill-${id}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2AABEE" stopOpacity={0.22}/><stop offset="100%" stopColor="#2AABEE" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#ffffff0c"/><XAxis dataKey="time" type="number" domain={['dataMin','dataMax']} scale="time" tickFormatter={n=>new Date(n*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} tick={{fill:'#8c9198',fontSize:10}} axisLine={false} tickLine={false} minTickGap={45}/><YAxis domain={['auto','auto']} orientation="right" tickFormatter={n=>price(n)} tick={{fill:'#8c9198',fontSize:10}} axisLine={false} tickLine={false} width={82}/><Tooltip labelFormatter={n=>new Date(Number(n)*1000).toLocaleString()} formatter={v=>[`${price(Number(v))} SOL`,'Price']} contentStyle={{background:'#202124',border:'1px solid #3b3d42',borderRadius:10,fontSize:12}}/><Area type="linear" dataKey="close" stroke="#2AABEE" strokeWidth={2} fill={`url(#market-fill-${id})`} dot={chart.length===1?{r:4,fill:'#2AABEE'}:false} activeDot={{r:4}} isAnimationActive={false}/></AreaChart></ResponsiveContainer>:<p>{error?'Retry to load the chart.':'No price data available yet.'}</p>}
  </div>
  <div className="market-caption"><span>{market?.candles.length?'Recent finalized trades · SOL prices':market?'Current on-chain price · No indexed trades yet':'Solana market data'}</span>{market&&<span>{market.indexing?'Loading more trades…':`Updated ${new Date(market.updatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`}</span>}</div>
  <div className="market-trades-head"><h3>Trade history</h3><span>Pump{market?.graduated?' / PumpSwap':''} · Finalized</span></div>
  {market?.trades.length?<div className="market-table-scroll"><table className="market-table"><thead><tr><th>Time</th><th>Type</th><th>SOL</th><th>{symbol}</th><th>Trader</th><th>Txn</th></tr></thead><tbody>{market.trades.map(t=><tr key={`${t.signature}:${t.eventIndex}`}><td><time title={new Date(t.time*1000).toLocaleString()}>{new Date(t.time*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time></td><td className={`trade-${t.side}`}>{t.side==='buy'?'Buy':'Sell'}</td><td>{asSOL(t.solLamports)}</td><td>{(Number(t.tokenRaw)/1e6).toLocaleString(undefined,{maximumFractionDigits:2})}</td><td><a href={`https://solscan.io/account/${t.wallet}${cluster}`} target="_blank" rel="noreferrer">{short(t.wallet)}</a></td><td><a href={`https://solscan.io/tx/${t.signature}${cluster}`} target="_blank" rel="noreferrer" aria-label={`View ${t.side} transaction on Solscan`}><ArrowUpRight size={14}/></a></td></tr>)}</tbody></table></div>:<p className="market-empty" role="status">{loading?'Loading trades…':error?'Trade history could not be loaded.':market?.indexing?'Indexing finalized transactions…':'No finalized trades found yet. New buys and sells will appear here automatically.'}</p>}
 </section>;
}
