'use client';
import {useEffect,useRef,useState} from 'react';
import {createChart,CandlestickSeries,HistogramSeries,ColorType,CrosshairMode,LineStyle,type UTCTimestamp,type IChartApi,type ISeriesApi} from 'lightweight-charts';
import {ArrowUpRight,RefreshCw,Maximize2,Minus,Plus} from 'lucide-react';
import {request,asSOL,usePlatform} from './platform-actions';
type Candle={time:number;open:number;high:number;low:number;close:number;volumeUsd:number;trades:number};
type Trade={signature:string;eventIndex:number;time:number;side:'buy'|'sell';wallet:string;solLamports:string;tokenRaw:string;priceUsd:number|null;volumeUsd:number|null};
export type Market={updatedAt:string;stale:boolean;indexing:boolean;spotPriceUsd:number|null;graduated:boolean;candles:Candle[];trades:Trade[];usdHistoryComplete:boolean;stats:{marketCapUsd:number|null;volume24hUsd:number|null;change24h:number|null;holders:number|null;holdersAt:string|null}};
export const usd=(n:number|null|undefined)=>n==null?'—':n===0?'$0':n<0.001?'$'+n.toFixed(10).replace(/0+$/,''):n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n<1?6:2});
const short=(s:string)=>`${s.slice(0,4)}…${s.slice(-4)}`;
export function TokenStats({market}:{market:Market|null}){
 const stats=market?.stats;const holderStale=!stats?.holdersAt||Date.now()-new Date(stats.holdersAt).getTime()>600000;
 return <dl className="token-stat-bar" aria-label="Token market statistics"><div><dt>Price <small>USD</small></dt><dd>{usd(market?.spotPriceUsd)}</dd></div><div><dt>Market cap</dt><dd>{usd(stats?.marketCapUsd)}</dd></div><div><dt>24h change</dt><dd className={(stats?.change24h??0)<0?'trade-sell':'trade-buy'}>{stats?.change24h==null?'—':`${stats.change24h>0?'+':''}${stats.change24h.toFixed(2)}%`}</dd></div><div><dt>24h volume</dt><dd>{market?.indexing?<small>Indexing…</small>:usd(stats?.volume24hUsd)}</dd></div><div title="Unique wallet owners with positive balances. Program-controlled accounts are excluded."><dt>Holders</dt><dd>{holderStale?'—':stats?.holders?.toLocaleString()??'—'}</dd></div></dl>;
}
function Candles({candles,interval,spot}:{candles:Candle[];interval:number;spot:number|null}){
 const container=useRef<HTMLDivElement>(null),chart=useRef<IChartApi|null>(null),series=useRef<ISeriesApi<'Candlestick'>|null>(null),volume=useRef<ISeriesApi<'Histogram'>|null>(null),fitted=useRef(false);const [hover,setHover]=useState<Candle|null>(null);
 useEffect(()=>{
  if(!container.current)return;
  const api=createChart(container.current,{autoSize:true,height:390,layout:{background:{type:ColorType.Solid,color:'#171B20'},textColor:'#AAB4BE',fontFamily:'Inter, sans-serif',fontSize:12,attributionLogo:true},grid:{vertLines:{color:'#252D34'},horzLines:{color:'#252D34'}},crosshair:{mode:CrosshairMode.Normal,vertLine:{color:'#8298A8',style:LineStyle.Dashed,labelBackgroundColor:'#2B3944'},horzLine:{color:'#8298A8',style:LineStyle.Dashed,labelBackgroundColor:'#2B3944'}},rightPriceScale:{borderColor:'#34414A',scaleMargins:{top:0.10,bottom:0.27}},timeScale:{borderColor:'#34414A',timeVisible:true,secondsVisible:false,rightOffset:8,barSpacing:10,minBarSpacing:4},localization:{priceFormatter:(n:number)=>usd(n)}});
  const prices=api.addSeries(CandlestickSeries,{upColor:'#39C894',downColor:'#EB7181',wickUpColor:'#39C894',wickDownColor:'#EB7181',borderVisible:false,lastValueVisible:true,priceLineVisible:false,priceFormat:{type:'custom',minMove:0.000000000001,formatter:(n:number)=>usd(n)}});
  const volumes=api.addSeries(HistogramSeries,{priceFormat:{type:'volume'},priceScaleId:'volume',lastValueVisible:false,priceLineVisible:false});volumes.priceScale().applyOptions({scaleMargins:{top:0.78,bottom:0},visible:false});
  api.subscribeCrosshairMove(param=>{const p=param.seriesData.get(prices);if(p&&'open' in p)setHover({...p,time:Number(param.time),volumeUsd:0,trades:0} as Candle);else setHover(null);});chart.current=api;series.current=prices;volume.current=volumes;fitted.current=false;
  return()=>{api.remove();chart.current=null;series.current=null;volume.current=null};
 },[interval]);
 useEffect(()=>{series.current?.setData(candles.map(c=>({...c,time:c.time as UTCTimestamp})));volume.current?.setData(candles.map(c=>({time:c.time as UTCTimestamp,value:c.volumeUsd,color:c.close>=c.open?'#39C89466':'#EB718166'})));if(candles.length&&!fitted.current){chart.current?.timeScale().fitContent();fitted.current=true;}},[candles,interval]);
 useEffect(()=>{if(!series.current||spot===null||spot<=0||!candles.length)return;const line=series.current.createPriceLine({price:spot,color:'#2AABEE',lineWidth:1,lineStyle:LineStyle.Dashed,axisLabelVisible:true,title:'LAST'});return()=>{series.current?.removePriceLine(line)}},[spot,candles.length,interval]);
 const zoom=(factor:number)=>{const scale=chart.current?.timeScale(),range=scale?.getVisibleLogicalRange();if(!range)return;const pad=(range.to-range.from)*factor;scale?.setVisibleLogicalRange({from:range.from+pad,to:range.to-pad});};
 const selected=hover||candles.at(-1);
 return <><div className="candle-readout" aria-live="off">{selected?(['open','high','low','close'] as const).map((key,i)=><span key={key}>{['O','H','L','C'][i]} <b>{usd(selected[key])}</b></span>):<span>No finalized USD candles yet</span>}<div className="chart-tools"><button onClick={()=>chart.current?.timeScale().scrollToPosition(0,false)} aria-label="Jump to latest candle" title="Latest">Latest</button><button onClick={()=>chart.current?.timeScale().fitContent()} aria-label="Fit all price history" title="Fit chart"><Maximize2 size={15}/></button><button onClick={()=>zoom(.15)} aria-label="Zoom in" title="Zoom in"><Plus size={15}/></button><button onClick={()=>zoom(-.18)} aria-label="Zoom out" title="Zoom out"><Minus size={15}/></button></div></div><div className="chart-canvas-wrap"><div ref={container} className="candlestick-canvas" role="img" aria-label="Interactive USD candlestick chart with trade volume. Drag to pan, scroll to zoom, or use the chart controls."/>{!candles.length&&<div className="chart-no-trades" role="status">Price candles appear after finalized trades are indexed.</div>}</div></>;
}
export function TokenMarket({id,symbol,onUpdate}:{id:string;symbol:string;onUpdate?:(market:Market)=>void}){
 const {runtime}=usePlatform();const [market,setMarket]=useState<Market|null>(null),[error,setError]=useState(''),[interval,setIntervalValue]=useState(60),[retry,setRetry]=useState(0),[loading,setLoading]=useState(true);const update=useRef(onUpdate);update.current=onUpdate;
 useEffect(()=>{let active=true,busy=false;setLoading(true);setError('');async function refresh(){if(busy)return;busy=true;try{const next=await request<Market>(`/api/public/token/${encodeURIComponent(id)}/market?interval=${interval}`);if(active){setMarket(next);update.current?.(next);setError('');}}catch{if(active)setError('Market data is temporarily unavailable.')}finally{busy=false;if(active)setLoading(false);}}void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},15000);return()=>{active=false;clearInterval(timer)}},[id,interval,retry]);
 const cluster=runtime?.cluster==='devnet'?'?cluster=devnet':'';
 return <section className="live-market" aria-label={`${symbol} price and trades`}>
 <div className="market-heading"><div><span>{symbol} / USD {market?.spotPriceUsd&&!market.stale&&<i className="chart-live" aria-label="Live price"/>}</span><strong>{usd(market?.spotPriceUsd)}</strong></div><div className="market-intervals" aria-label="Chart interval">{[[60,'1m'],[300,'5m'],[3600,'1h']].map(([value,label])=><button key={value} aria-pressed={interval===value} onClick={()=>setIntervalValue(Number(value))}>{label}</button>)}</div></div>
 {(error||market?.stale)&&<div className="market-message" role="status"><span>{error||'Showing the last available market data.'}</span><button className="text-link" onClick={()=>setRetry(n=>n+1)}><RefreshCw size={13}/> Retry</button></div>}
 {loading&&!market?<div className="market-chart"><p role="status">Loading on-chain market data…</p></div>:<Candles candles={market?.candles||[]} interval={interval} spot={market?.spotPriceUsd||null}/>}
 <div className="market-caption"><span>{market?.indexing?'Indexing finalized trades…':!market?.usdHistoryComplete?'Updating USD history…':'Price · USD'}</span><span>Volume · USD</span></div>
 <div className="market-trades-head"><h3>Trade history</h3><span>Pump{market?.graduated?' / PumpSwap':''} · Finalized</span></div>
 {market?.trades.length?<div className="market-table-scroll"><table className="market-table"><thead><tr><th>Time</th><th>Type</th><th>Price · USD</th><th>Total · USD</th><th>SOL</th><th>{symbol}</th><th>Trader</th><th>Txn</th></tr></thead><tbody>{market.trades.map(t=><tr key={`${t.signature}:${t.eventIndex}`}><td><time title={new Date(t.time*1000).toLocaleString()}>{new Date(t.time*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time></td><td className={`trade-${t.side}`}>{t.side==='buy'?'Buy':'Sell'}</td><td>{usd(t.priceUsd)}</td><td>{usd(t.volumeUsd)}</td><td>{asSOL(t.solLamports)}</td><td>{(Number(t.tokenRaw)/1e6).toLocaleString(undefined,{maximumFractionDigits:2})}</td><td><a href={`https://solscan.io/account/${t.wallet}${cluster}`} target="_blank" rel="noreferrer">{short(t.wallet)}</a></td><td><a href={`https://solscan.io/tx/${t.signature}${cluster}`} target="_blank" rel="noreferrer" aria-label={`View ${t.side} transaction on Solscan`}><ArrowUpRight size={14}/></a></td></tr>)}</tbody></table></div>:<p className="market-empty" role="status">{loading?'Loading trades…':error?'Trade history could not be loaded.':market?.indexing?'Indexing finalized transactions…':'No finalized trades found yet.'}</p>}
 </section>;
}
